### ISSUE TITLE
API Routes

### ISSUE THREAD

**Issue by jntolman** [dsasmblr/eDreamTeam#48]
API GET routes for (all, single by id) for (easies, funnies, hards, indicies, intermediates, quotes, reddits)

**Comment by bensass123** [comment]
is there a reason we need routes to display all?

**Comment by jntolman** [comment]
i can write the api routes, this way you can focus on html routes with handlebars and if you're building the pages on the front end just know that you can get one item by id at /item/id and if you build the pages on the server you can make the queries in those routes and don't need to use the api

**Comment by bensass123** [comment]
I have all the api routes returning the item the way you describe on my branch, I did that last  night but forgot to push it up. It's up now. I need to add the stormpath functionality, deal with storing the indices and other data (increase score on post).  The main html route will be one static page in the main directory, it will serve up content by ajax calls to the various api endpoints. We will need to add a login button to the static page that Stephen has already created, along w these ajax calls to have a functioning page. Then we will need to incorporate the stormpath stuff into the api routes to verify login and save and call index and post score data.

1. Push da memes to img/funny folder (will consult w where to add funny in design w stephen)
2. get stormpath functionality working on routes
3. change all api endpoints to return based on current index within customuserdata for each item. will also increment the particular index

4 [front-end]ajax calls for each endpoint 
5. [front-end]create front-end handlebars templates
6. [front-end]populate templates accordingly

I can do all of this and was planning on starting in an hour or so. But if anyone wants to work on 2,4,5, or 6 that would be awesome, I'd like to finish off the routing, it is my beautiful little baby and I just need to pat it with a little baby powder.

**Comment by bensass123** [comment]
since i broke this down into smaller tasks im going to mark this one as closed
