### ISSUE TITLE
get stormpath functionality working on routes

### ISSUE THREAD

**Issue by bensass123** [dsasmblr/eDreamTeam#61]
get customdata returning and being set, get loginverification working

**Comment by jntolman** [comment]
Theresa has a users route she is working on that will set the customData and the config has been updated to hit this route upon completion of registration

**Comment by bensass123** [comment]
setup of customData storage and stormpath completed, routes updated to return next object on api/quotes/current and previous one on api/quotes/prev.

**Comment by bensass123** [comment]
awesome, looks like all i will have to do is change 1 line in my routes, and match my variable names w hers. no problemo
